controller_manager_ns: pr2_controller_manager
controller_list:
 - name: r_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - r_shoulder_pan_joint
     - r_shoulder_lift_joint
     - r_upper_arm_roll_joint
     - r_elbow_flex_joint
     - r_forearm_roll_joint
     - r_wrist_flex_joint
     - r_wrist_roll_joint
 - name: l_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - l_shoulder_pan_joint
     - l_shoulder_lift_joint
     - l_upper_arm_roll_joint
     - l_elbow_flex_joint
     - l_forearm_roll_joint
     - l_wrist_flex_joint
     - l_wrist_roll_joint
 - name: r_gripper_controller
   action_ns: gripper_action
   type: GripperCommand
   default: true
   joints:
     - r_gripper_joint
     - r_gripper_l_finger_joint 
     - r_gripper_motor_screw_joint 
     - r_gripper_motor_slider_joint
 #- name: r_gripper_controller
  # action_ns: gripper_action   #gripper_action 
   #type: GripperCommand     #GripperCommand
   #default: false
   #joints:
    # - r_gripper_motor_screw_joint
     #- r_gripper_motor_slider_joint
     #- r_gripper_l_finger_joint   #en Gazebo
     #- r_gripper_r_finger_joint   #en Gazebo
     #- r_gripper_r_finger_tip_joint # s칩lo en Gazebo
     #- r_gripper_l_finger_tip_joint # s칩lo en Gazebo
     #- r_gripper_palm_joint #A침adido, s칩lo gazebo
     #- r_gripper_led_joint
     #- r_gripper_motor_accelerometer_joint
     #- r_gripper_tool_joint
     #- r_gripper_joint
